# Generated by Django 5.1.1 on 2024-09-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_max', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profesor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
